### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by javsalgar** [ukfast/go-durationstring#2]
### What is the feature?

We need to know the license of the application so our license scanner validates using this package.

**Comment by Raffo** [comment]
+1 this is causing problems for ExternalDNS that has an indirect dependency on this due to importing https://github.com/ukfast/sdk-go . 

/cc @rjhenry who contributed the code to ExternalDNS.

**Comment by 0x4c6565** [comment]
Added license. Tagged [https://github.com/ukfast/go-durationstring/releases/tag/v1.0.2](v1.0.2)
